[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-flake-exercise"
version = "0.1.0"
dependencies = [
    # === EDIT HERE (Exercise 2) ===
    # Add the required dependencies (e.g. flask) here if you need it!
]